### ISSUE TITLE
Encoding parameter 

### ISSUE THREAD

**Issue by benjithedalilama** [wting/srt-resync#1]
I get an error when trying to run the script saying:

```shell
srt-resync ben-imadali$ python srt-resync -o 12 ../Downloads/Bakjwi\ Thirst\ .DVDRip.BeStDivX.en.srt 
Traceback (most recent call last):
  File "srt-resync", line 87, in <module>
    modify_file(parse_options())
  File "srt-resync", line 71, in modify_file
    with open(out_filename, 'w', encoding = 'utf-8') as out:
**TypeError: 'encoding' is an invalid keyword argument for this function**
```

I just removed the encoding = 'utf-8' from the modify_file() function and it works smoothly.

**Comment by wting** [comment]
The `encoding` parameter is supported in Python 3, and as referenced at the top of the [script](https://github.com/wting/srt-resync/blob/master/srt-resync#L1).

You have this issue because you're using Python 2.
